# Netlify Build Configuration
[build]
  base = "Backend/frontend"
  publish = "Backend/frontend/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://storeweb-mern.onrender.com"
